{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana-pdf-exporter.fullname" . }}-credentials
  labels:
    {{- include "grafana-pdf-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  GRAFANA_USER: {{ .Values.grafana.user | quote }}
  GRAFANA_PASSWORD: {{ .Values.grafana.password | quote }}
{{- end }}
